- name: install nginx server
  ansible.builtin.package:
    name: nginx
    state: present
- name: start nginx server
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: import roles form comman
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req.yaml

- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: 
    - restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted